/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaterActivitiesRouteImport } from './routes/water-activities'
import { Route as LandActivitiesRouteImport } from './routes/land-activities'
import { Route as ExcursionsRouteImport } from './routes/excursions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as ActivitiesSlugRouteImport } from './routes/activities.$slug'

const WaterActivitiesRoute = WaterActivitiesRouteImport.update({
  id: '/water-activities',
  path: '/water-activities',
  getParentRoute: () => rootRouteImport,
} as any)
const LandActivitiesRoute = LandActivitiesRouteImport.update({
  id: '/land-activities',
  path: '/land-activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcursionsRoute = ExcursionsRouteImport.update({
  id: '/excursions',
  path: '/excursions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const ActivitiesSlugRoute = ActivitiesSlugRouteImport.update({
  id: '/activities/$slug',
  path: '/activities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/excursions': typeof ExcursionsRoute
  '/land-activities': typeof LandActivitiesRoute
  '/water-activities': typeof WaterActivitiesRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/excursions': typeof ExcursionsRoute
  '/land-activities': typeof LandActivitiesRoute
  '/water-activities': typeof WaterActivitiesRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/excursions': typeof ExcursionsRoute
  '/land-activities': typeof LandActivitiesRoute
  '/water-activities': typeof WaterActivitiesRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/excursions'
    | '/land-activities'
    | '/water-activities'
    | '/activities/$slug'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/excursions'
    | '/land-activities'
    | '/water-activities'
    | '/activities/$slug'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/excursions'
    | '/land-activities'
    | '/water-activities'
    | '/activities/$slug'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  ExcursionsRoute: typeof ExcursionsRoute
  LandActivitiesRoute: typeof LandActivitiesRoute
  WaterActivitiesRoute: typeof WaterActivitiesRoute
  ActivitiesSlugRoute: typeof ActivitiesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/water-activities': {
      id: '/water-activities'
      path: '/water-activities'
      fullPath: '/water-activities'
      preLoaderRoute: typeof WaterActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land-activities': {
      id: '/land-activities'
      path: '/land-activities'
      fullPath: '/land-activities'
      preLoaderRoute: typeof LandActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excursions': {
      id: '/excursions'
      path: '/excursions'
      fullPath: '/excursions'
      preLoaderRoute: typeof ExcursionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/activities/$slug': {
      id: '/activities/$slug'
      path: '/activities/$slug'
      fullPath: '/activities/$slug'
      preLoaderRoute: typeof ActivitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  ExcursionsRoute: ExcursionsRoute,
  LandActivitiesRoute: LandActivitiesRoute,
  WaterActivitiesRoute: WaterActivitiesRoute,
  ActivitiesSlugRoute: ActivitiesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
